jobs:
- job: PUBLISH_WEBSITE_DOWNLOADS
  condition: eq(variables.publishDownloads, true)
  dependsOn: 
    - BUILD_MAC_PROJECTS
    - BUILD_WIN_PROJECTS
    
  strategy:
    matrix:
      NANOVG:
        graphics: 'NANOVG'
        # condition: eq(variables.buildNANOVG, true)
      # CAIRO:
      #   graphics: 'CAIRO'
      #   condition: eq(variables.buildCAIRO, true)
      # LICE:
      #   graphics: 'LICE'
      #   condition: eq(variables.buildLICE, true)
      # AGG:
      #   graphics: 'AGG'
      #   condition: eq(variables.buildAGG, true)
        
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: none

  - template: azure-projects.yml
    parameters:
      platform: Scripts/azure-project-upload.yml
      graphics: $(graphics)
      platformStr: 'MAC'
  
  - template: azure-projects.yml
    parameters:
      platform: Scripts/azure-project-upload.yml
      graphics: $(graphics)
      platformStr: 'WIN'

- job: PUBLISH_WEBSITE_PAGES
  condition: eq(variables.publishWebsite, true)
  dependsOn: 
    - BUILD_WEB_PROJECTS

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: none

  - bash: |
      git clone https://olilarkin:$GITHUB_PAT@github.com/iPlug2/iPlug2.github.io.git $BUILD_SOURCESDIRECTORY
    displayName: Clone website repo
    env:
      GITHUB_PAT: $(GITHUB_PAT)

  - template: azure-projects.yml
    parameters:
      platform: Scripts/azure-project-upload.yml
      graphics: 'NANOVG'
      platformStr: 'WEB'

  - template: azure-projects.yml
    parameters:
      platform: Scripts/azure-project-upload.yml
      graphics: 'CANVAS'
      platformStr: 'WEB'